SELECT ?v0 ?v8 WHERE {
    ?v0 <http://www.w3.org/1999/xhtml/vocab#stylesheet> ?v1.
    ?v0 <http://www.w3.org/1999/xhtml/vocab#icon> ?v2.
    ?v0 <http://ogp.me/ns#description> ?v3.
    ?v0 <http://www.w3.org/1999/xhtml/vocab#next> ?v4.
    ?v0 <http://ogp.me/ns#title> ?v5.
    ?v0 <http://ogp.me/ns#url> ?v6.
    ?v0 <http://ogp.me/ns#type> ?v7.
    ?v0 <http://www.w3.org/1999/xhtml/vocab#prev> ?v8.
} LIMIT 1000000
