SELECT ?v0 ?v8 WHERE {
    ?v0 <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> ?v1.
    ?v1 <http://purl.org/dc/terms/hasPart> ?v2.
    ?v2 <http://www.metalex.eu/metalex/2008-05-02#variant> ?v3.
    ?v3 <http://www.metalex.eu/metalex/2008-05-02#fragment> ?v4.
    ?v4 <http://www.metalex.eu/metalex/2008-05-02#fragment> ?v5.
    ?v5 <http://xmlns.com/foaf/0.1/primaryTopic> ?v6.
    ?v6 <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> ?v7.
    ?v7 <http://purl.org/dc/terms/hasPart> ?v8.
} LIMIT 1000000
